Задачи для самостоятельного решения
js-tasks-ru/vue-20231109_vladsvir888 pull request #2
Opened 2023-11-24 20:48 UTC by vladsvir888

Добавлены задачи из модуля "Компоненты" + фикс v-cloak

2023-11-24 20:49 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-11-24 23:44 UTC, ShGKme requested changes

2023-11-24 23:44 UTC, ShGKme commented on 02-components/01-CounterButtonComponent/CounterButton.js
> +  template: `<button @click="$emit('update:count', count + 1)" type="button">{{ count || '0' }}</button>`,
Значение по умолчанию должно быть задано в самом описании пропса, а не в каждом месте его использования.

2023-11-24 23:44 UTC, ShGKme commented on 02-components/07-PageMeetup/components/PageMeetup.js
> +        <UiAlert>Test Error</UiAlert>
`'Test Error'` - это не полученная ошибка, а текст ошибки из соответствующего теста... Настоящий текст ошибки можно достать из исключения, которое выбрасывает функция `fetchMeetupById`. 

Сообщение ошибки можно получить из свойства `error.message` у JS ошибки: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/message

2023-11-25 09:34 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-11-25 09:36 UTC, vladsvir888 commented
@ShGKme спасибо, внес корректировки

2023-11-25 11:24 UTC, ShGKme approved these changes
Все задачи приняты 👍

2023-11-25 11:26 UTC, merged