Задачи для самостоятельного решения
js-tasks-ru/vue-20231109_vladsvir888 pull request #3
Opened 2023-12-01 17:53 UTC by vladsvir888

Сделаны задачи из модуля SFC и первые три задачи из модуля @vue/cli

2023-12-01 17:54 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-12-01 20:28 UTC, ShGKme requested changes
В TheToaster требуется немного переработать интерфейс компонента. Остальные задаич приняты.

2023-12-01 20:28 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/TheToaster.vue
> +        id: Date.now(),
Лучше не использовать `Date.now()` в качестве идентификатора. Он не гарантирует уникальность. Два вместе добавленнытоста могут быть добавлены за 1мс.

Вместо этого можно использовать случайные значения или автоинкремент.

2023-12-01 20:28 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/UIToast.vue
> +    <button v-if="closable" @click="$emit('close', id)" class="toast__close" aria-label="Close">
С событием не нужно отдавать `id`, который этому компоненту в целом не нужен. Его родитель итак знает, у какого тоста порождается событие `close`. Он знает этот `id`, который сейчас получается вместе с событием, потому что он сам же ему его отдаёт. Сейчас `id` просто получается от родителя и отправляется ему же обратно, больше никак не используясь.

При этом не может возникнуть ситуации, когда один тост будет сообщать об удалении какого-то другого тоста с другим ID.

Поэтому лучше не передавать лишних данных в событиях.

2023-12-01 20:28 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/TheToaster.vue
> +    ></UIToast>
Здесь `TheToaster` передаёт в `UiToast` `:id="toast.id"`, а потом его же ловит и использует в `@close="removeToast"`. Вместо отправки ID по кругу можно явно передать его сразу: `@close="removeToast(toast.id)"`.

2023-12-01 20:28 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/TheToaster.vue
> +        },
Здесь в данных компонента передаётся класс и иконка в тост. Получается не очень удобный интерфейс компонента. Пользователь компонента должен знать, какое название иконки передавать и какое название класса (из внутренней реализации компонента) требуется передать для тоста каждого типа. Это неудобно и приведёт к тому, что в разных местах приложения одинаковые тосты будут иметь разный стиль или иконки.

2023-12-01 20:28 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/TheToaster.vue
> +      :class="toast.className"
В итоге здесь на узел устанавливается класс, стили для которого не описаны в текущем компоненте и которые по идее не должны работать в этом компоненте. Они работают за счёт протекания scoped стилей во Vue.

2023-12-01 20:28 UTC, ShGKme commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
> +}
Чтобы не копировать стили, можно переиспользовать уже готовый компонент (реализован в задаче предыдущей темы)

2023-12-01 20:28 UTC, ShGKme commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
> +    },
Здесь хорошо подходит метод массива [some](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/some)

2023-12-01 20:29 UTC, ShGKme commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
> +    },
Также это свойство хранит true/false флаг, но названо как будто хранит название класса.

2023-12-01 23:22 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-12-01 23:23 UTC, vladsvir888 commented
@ShGKme спасибо за фидбек, сделал коммит с фиксом

2023-12-03 14:41 UTC, ShGKme approved these changes

2023-12-03 14:42 UTC, merged